apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleship-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: battleship-server
  template:
    metadata:
      labels:
        app: battleship-server
    spec:
      containers:
        - name: battleship-server
          image: anmaldev/battleship-server:v.1.0.3
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: battleship-server-service
spec:
  selector:
    app: battleship-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30201
  type: NodePort
