apiVersion: apps/v1
kind: Deployment
metadata:
  name: owstestproj-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: owstestproj
  template:
    metadata:
      labels:
        app: owstestproj
    spec:
      containers:
        - name: owstestproj
          image: anmaldev/owstestproj:ac19f6c
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: owstestproj-service
spec:
  selector:
    app: owstestproj
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
  type: NodePort
