apiVersion: apps/v1
kind: Deployment
metadata:
  name: owstestproj-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: owstestproj
  template:
    metadata:
      labels:
        app: owstestproj
    spec:
      containers:
        - name: owstestproj
          image: anmaldev/owstestproj:262e42b
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__PINChatAuth
              valueFrom:
                secretKeyRef:
                  name: auth-connection-string
                  key: connection-string
            - name: ConnectionStrings__PINChatData
              valueFrom:
                secretKeyRef:
                  name: data-connection-string
                  key: connection-string
            - name: Secrets__SecurityKey
              valueFrom:
                secretKeyRef:
                  name: jwt-security-key
                  key: securitykey
            - name: Secrets__EncryptionKey
              valueFrom:
                secretKeyRef:
                  name: db-encryption-key
                  key: encryptionkey
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: owstestproj-service
spec:
  selector:
    app: owstestproj
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
  type: NodePort
