name: Update PINChat_Api

on:
  repository_dispatch:
    types:
      - update-version-pinchat-api

jobs:
  update-dep-yml:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Update pinchat-api.yml with new version
        run: |
          NEW_VERSION=$(echo ${{ github.event.client_payload.version }})

          sed -i "17s|.*|          image: anmaldev/pinchat-api:$NEW_VERSION|" Apps/pinchat-api.yml

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Apps/pinchat-api.yml
          git commit -m "Update version in pinchat-api.yml to $NEW_VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
