apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchat-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pinchat-api
  template:
    metadata:
      labels:
        app: pinchat-api
    spec:
      containers:
        - name: pinchat-api
          image: anmaldev/pinchat-api:na
          ports:
            - containerPort: 443
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pinchat-api-service
spec:
  selector:
    app: pinchat-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30000
  type: NodePort
