apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchat-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinchat-app
  template:
    metadata:
      labels:
        app: pinchat-app
    spec:
      containers:
        - name: pinchat-app
          image: anmaldev/pinchat-app:1be7c5c
          ports:
            - containerPort: 80
          env:
            - name: Encryption__Key
              valueFrom:
                secretKeyRef:
                  name: subtlecrypto-key
                  key: encryptionkey
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pinchat-app-service
spec:
  selector:
    app: pinchat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
