apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchat-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pinchat-server
  template:
    metadata:
      labels:
        app: pinchat-server
    spec:
      containers:
        - name: pinchat-server
          image: anmaldev/pinchat-server:439d91f
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pinchat-server-service
spec:
  selector:
    app: pinchat-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
