apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchat-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinchat-app
  template:
    metadata:
      labels:
        app: pinchat-app
    spec:
      containers:
        - name: pinchat-app
          image: anmaldev/pinchat-app:09c4f1b
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__PINChatAuth
              valueFrom:
                secretKeyRef:
                  name: auth-connection-string
                  key: connection-string
            - name: ConnectionStrings__PINChatData
              valueFrom:
                secretKeyRef:
                  name: data-connection-string
                  key: connection-string
            - name: Secrets__SecurityKey
              valueFrom:
                secretKeyRef:
                  name: jwt-security-key
                  key: securitykey
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pinchat-app-service
spec:
  selector:
    app: pinchat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
