apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchat-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinchat-server
  template:
    metadata:
      labels:
        app: pinchat-server
    spec:
      containers:
        - name: pinchat-server
          image: anmaldev/pinchat-chatserver:de7f0f9
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pinchat-server-service
spec:
  selector:
    app: pinchat-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
