apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchat-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pinchat-api
  template:
    metadata:
      labels:
        app: pinchat-api
    spec:
      containers:
        - name: pinchat-api
          image: anmaldev/pinchat-api:6108353
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__PINChatAuth
              valueFrom:
                secretKeyRef:
                  name: auth-connection-string
                  key: connection-string
            - name: ConnectionStrings__PINChatData
              valueFrom:
                secretKeyRef:
                  name: data-connection-string
                  key: connection-string
            - name: Secrets__SecurityKey
              valueFrom:
                secretKeyRef:
                  name: jwt-security-key
                  key: securitykey
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pinchat-api-service
spec:
  selector:
    app: pinchat-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
